function whole(){
    var dat=new Date();
    var seconds=dat.getSeconds();
    document.getElementById('sec').innerHTML=seconds;
    var milliseconds=dat.getMilliseconds();
    document.getElementById('milsec').innerHTML=milliseconds;

    var patracode=milliseconds*66;
    document.getElementById('patra-code').innerHTML=patracode;

    var contrynames=[
        "albania",
        "italy",
        "jorban",
        "libya",
        "brazil",
        "pakistan",
        "lesotho",
        "morocco",
        "china",
        "india",
        "angola",
        "iran",
        "korea",
        "liberia",
        "mali",
        "nepal",
        "greece",
        "mexico",
        "luxembrug",
        "tanzania",
        "iraq",
        "bhutan",
        "bulgaria",
        "colombia",
        "cuba",
        "egypt",
        "figi ",
        "gambia",
        "gibraltar",
        "gayana",
        "malawi",
        "nigeria",
        "russia",
        "saudi arabia",
        "switezland",
        "tunisia",
        "ukrain",
        "zimbia",
        "viet nam",
        "somalia", 
        "peru",
        "norway",
        "afghanistan",
        "australia",
        "kenza",
        "macao",
        "thailand",
        "malta",
        "labanon",
        "singapore",
        "iceland",
        "sapin",
        "poland",
        "senegal",
        "romania",
        "kuwait",
        "qatar",
        "france",
        "yemen",
        "turkey",
    ]
document.getElementById('contry').innerHTML=(contrynames[seconds]);

var mtrlavals=[
    "66",
    "60",
    "70",
    "60",
    "90",
    "77",
    "72",
    "70",
    "90",
    "60",
    "84",
    "60",
    "70",
    "60",
    "90",
    "61",
    "50",
    "70",
    "90",
    "60",
    "70",
    "60",
    "70",
    "60",
    "90",
    "54",
    "82",
    "70",
    "90",
    "60",
    "54",
    "60",
    "70",
    "60",
    "90",
    "86",
    "40",
    "70",
    "90",
    "60",
    "43",
    "60",
    "70",
    "60",
    "90",
    "50",
    "60",
    "70",
    "90",
    "60",
    "93",
    "60",
    "70",
    "60",
    "90",
    "80",
    "40",
    "70",
    "90",
    "60",
]


document.getElementById('mtr').value=(mtrlavals[seconds])

document.getElementById('mtrmem').value=(mtrlavals[seconds])

var ststusname=[
    "danger",    
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "danger",
    "danger",
    "normal",
    "normal",
    "normal",
    "danger",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "danger",
    "danger",
    "danger",
    "danger",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "danger",
    "danger",
    "normal",
    "normal",
    "normal",
    "normal",
    "danger",
    "danger",
    "normal",
    "normal",
    "normal",
    "normal",
    "danger",
    "danger",
    "normal",
    "normal",
    "normal",
    "normal",
    "danger",
    "danger",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "normal",
    "danger",
]
    document.getElementById('status').innerHTML=(ststusname[seconds])
if(document.getElementById('status').innerHTML==="danger"){
    document.getElementById('status').className ="redcolor";
}
else{
    document.getElementById('status').className ="whitecolor";
}

var abc=["qm3fghxccjgg",
"wn1fghwertyd",
"eb3a66lpasdg",
"rv8h44erfggh",
"tc7g4gasdryt",
"yx7t55polkmc",
"uz6dd4qwertf",
"il6drydfghjk",
"oj5rfgertybv",
"ph6selertre3",
"ag4sjbvtyt56",
"sf3rr5lopasc",
"dd1df5tevnjk",
"fs23vvsnnys1",
"ga3dhsderrv6",
"hp9de2jqwess",
"jo56ytgfttfs",
"ki83rgdtebgf",
"ku0xc3dfrggf",
"ly58kfdupl65",
"zt6vfthydbv5",
"xr9gt5plme34",
"ce298u77trvf",
"vw4kpdgtgrf0",
"dfdfffbq1qm3",
"dyheytna3sf4",
"kudg5dmd2gt4",
"qm3fghxccjgg",
    "wn1fghwertyd",
    "eb3a66lpasdg",
    "rv8h44erfggh",
    "tc7g4gasdryt",
    "yx7t55polkmc",
    "uz6dd4qwertf",
    "il6drydfghjk",
    "oj5rfgertybv",
    "ph6selertre3",
    "ag4sjbvtyt56",
    "sf3rr5lopasc",
    "dd1df5tevnjk",
    "fs23vvsnnys1",
    "ga3dhsderrv6",
    "hp9de2jqwess",
    "jo56ytgfttfs",
    "ki83rgdtebgf",
    "ku0xc3dfrggf",
    "ly58kfdupl65",
    "zt6vfthydbv5",
    "xr9gt5plme34",
    "ce298u77trvf",
    "vw4kpdgtgrf0",
    "dfdfffbq1qm3",
    "dyheytna3sf4",
    "kudg5dmd2gt4",
    "qm3fghxccjgg",
    "wn1fghwertyd",
    "eb3a66lpasdg",
    "rv8h44erfggh",
    "tc7g4gasdryt",
    "yx7t55polkmc",
    "uz6dd4qwertf",
    "il6drydfghjk",
    "oj5rfgertybv",
    "ph6selertre3",
    "ag4sjbvtyt56",
    "sf3rr5lopasc",
    "dd1df5tevnjk",
    "fs23vvsnnys1",
    "ga3dhsderrv6",
    "hp9de2jqwess",
    "jo56ytgfttfs",
    "ki83rgdtebgf",
    "ku0xc3dfrggf",
    "ly58kfdupl65",
    "zt6vfthydbv5",
    "xr9gt5plme34",
    "ce298u77trvf",
    "vw4kpdgtgrf0",
    "dfdfffbq1qm3",
    "dyheytna3sf4",
    "kudg5dmd2gt4",
]
document.getElementById('binary').innerHTML=(abc[seconds])

var resulsintxt=[
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail ",
    "pass",
    "pass",
    "pass",
    "pass",
    "fail",
    "pass",
    "pass",
    "pass",
    "pass",
    " ",
]

document.getElementById('result').innerHTML=resulsintxt[seconds]

var errortxt=[
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
    " ",
    "not found",
]
document.getElementById('errors').innerHTML=errortxt[seconds]

  
var newmillsec=dat.getMilliseconds();
var newday=(newmillsec / 40).toFixed(0)
document.getElementById('totalaccounts').innerHTML=newday
 
var membersname=[
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    "john martin",
    "marry agnis",
    "dark devil",
    "silent joker",
    "adam",
    

]
document.getElementById('MEMBERS').innerHTML=membersname[seconds]


}




setInterval(whole ,10)